curvlinops/_base.py, curvlinops/gradient_moments.py, test/cases.py, test/test_gradient_moments.py, test/test_hessian.py, test/utils.py
- Tweak tolerances for tests to pass also for regression problems
- Minor improvements in type annotations and docstrings
=> [ADD] Regression test cases

README.md, curvlinops/__init__.py, curvlinops/submatrix.py, docs/rtd/conf.py, docs/rtd/linops.rst, test/test_submatrix.py, test/test_submatrix_on_curvatures.py
Given a linear operator `A`, the `SubmatrixLinearOperator` class allows
constructing the linear operator for `A[row_idxs, :][:, col_idxs]`.
The sub-matrix can be changed after initialization using the
`set_submatrix` method.
=> [ADD] Support for taking sub-matrices of linear operators

curvlinops/examples/functorch.py, setup.cfg
Updates the dependencies such that BackPACK with PyTorch>=2 is used.
Refactors the `functorch` utilities to use the new API from `torch.func`.
Removes dependency from separate `functorch` package.
=> [REF] Use built in functorch, use BackPACK 1.6

curvlinops/kfac.py, test/conftest.py, test/test_kfac.py
Resolves #46.
I have already added a `'type-2'` option for the `fisher_type` argument. Not sure if I like the name since this terminology is not very common, but using `'exact'` instead lead to confusion before.
=> [ADD] Support for empirical Fisher in KFAC

curvlinops/kfac.py, test/test_kfac.py, test/utils.py
Eventually, this will resolve #53.
At the moment, I am struggling to get the tests running and would benefit from a second pair of eyes to look through the code. At the moment, the tests seem to execute for both `separate_weight_and_bias = [False, True]`, but the matrix produced by KFAC is wrong for `True`.
I believe this is related to the order of parameters. But I think I am actually arranging them in the correct order 😂, so maybe I'm barking up the wrong tree. In any case, it would be great if you could skim the code and look for anything obvious I missed.
=> [ADD] Option to treat weight and bias of a layer jointly in KFAC

curvlinops/kfac.py, test/test_kfac.py
=> [ADD] Support KFAC if the network has inplace activations

curvlinops/kfac.py, curvlinops/kfac_utils.py, docs/rtd/index.rst, docs/rtd/internals.rst, test/conftest.py, test/test_kfac.py
Resolves #49.
Note: I can't immediately see anymore why the implementation for `CrossEntropyLoss` works like this, will have to think about it, but should be correct.
=> [ADD] Support for KFAC with type-2 Fisher

curvlinops/kfac.py, test/test_kfac.py, test/utils.py
Resolves #60.
This implements K-FAC-expand for linear layers with >2d inputs. Will address #50 in a follow-up PR. Also, I already added the `loss_average` keyword for the correct scaling of the gradient covariance.
=> Support KFAC for >2d model outputs

curvlinops/kfac.py, test/conftest.py, test/kfac_cases.py, test/test_kfac.py, test/utils.py
Resolves #50.
This PR is based on #62 which should be reviewed first. I will tackle #45 next and directly implement expand and reduce (will reuse most of the code for linear modules since it is almost identical).
=> Add support for KFAC-expand and KFAC-reduce for `Linear` modules

curvlinops/kfac.py, curvlinops/kfac_utils.py, setup.cfg, test/conftest.py, test/kfac_cases.py, test/test_kfac.py, test/utils.py
Resolves #45.
This review is based on #62 and #63 which should be reviewed first. I took the `extract_patches` and `extract_averaged_patches` from the SINGD repo, maybe we should add a reference.
_Note: Currently one of the tests fails due to numerical issues (it passes locally). -> Fixed by changing the `rtol` for the KFAC for weight sharing layers test from 1e-5 to 1e-4. Not ideal, but should hopefully be fine._
=> Add support for KFAC for `Conv2d` modules

curvlinops/_base.py, curvlinops/fisher.py, curvlinops/jacobian.py, curvlinops/kfac.py
At the moment, the number of data points is inferred by a pass through the data loader.
This can become a bottleneck on compute clusters when multiple jobs access the same data set in parallel (experience from a recent ICML submission on the Vector cluster).
To resolve this, the PR adds an optional argument `num_data` to all non-experimental linear operators which allows to avoid the data set traversal.
=> [ADD] Option to specify number of data points

curvlinops/_base.py, curvlinops/examples/utils.py, curvlinops/experimental/activation_hessian.py, curvlinops/fisher.py, curvlinops/ggn.py, curvlinops/gradient_moments.py, curvlinops/hessian.py, curvlinops/inverse.py, curvlinops/jacobian.py, curvlinops/kfac.py, test/test_inverse.py
**Warning:** This is a big refactoring and it will require some iterations to reduce complexity.
Please complain about anything that is incomprehensible, and check for outdated/unclear docstrings.
Currently, all linear operators implement how to multiply with a single vector (`_matvec`).
Multiplying onto more than one vector is simply iterating over the vectors one by one (`_matmat`).
This adds a lot of sweeps through a data set which can be avoided by implementing matrix-matrix,
rather than matrix-vector multiplication.
This PR changes the base class implementation from `_matvec` to `_matmat`.
=> [REF] Implement `_matmat` instead of `_matvec`

curvlinops/_base.py, curvlinops/hessian.py, curvlinops/utils.py, test/test_hessian.py, test/test_utils.py
Instead of multiplying with the Hessian w.r.t. the concatenation of all flattened params, this feature allows
breaking the parameters into smaller blocks and multiplying with the implied block-diagonal Hessian approximation.
=> [ADD] Support block-diagonal Hessian approximation

curvlinops/fisher.py, curvlinops/kfac.py
The device setting during sampling in `MCFisherLinearOperator` and `KFACLinearOperator` is currently broken. This is because `self._generator` will be created with `device="cpu"` to run `_check_deterministic()` and later it is only checked if `self._generator is None`. To fix this, we simply check `if self._generator.device != self._device` as well.
Moreover, the device of `std` was not set explicitly in one place.
=> [FIX] `Generator` device for sampling

curvlinops/inverse.py, curvlinops/kfac.py, test/test_inverse.py, test/test_kfac.py
Addresses #71, but only for the `KFACLinearOperator` and `KFACInverseLinearOperator`.
`KFACLinearOperator`/`KFACInverseLinearOperator` is arguably the only linear operator here that is likely to be used for preconditioned-gradient methods for large scale neural networks. Therefore, adding `torch_matmat` and `torch_matvec` methods seem like a simple solution to avoid unnecessary device transfers, which are a bottleneck for this use case. However, this doesn't address the issue in general.
=> Allow for matrix-matrix and matrix-vector products with `KFACLinearOperator` and `KFACInverseLinearOperator` without converting to numpy

curvlinops/kfac.py, test/conftest.py, test/kfac_cases.py, test/test_inverse.py, test/test_kfac.py
Add a `fisher_type` to implement the preconditioner used for [FOOF](https://arxiv.org/abs/2201.12250). This represents an extreme value for this argument since we only do a forward pass, compute the input covariances, and set the gradient covariances to identity matrices.
=> Add `fisher_type="forward-only"` (FOOF method) option to `KFACLinearOperator`

curvlinops/fisher.py, curvlinops/kfac.py, curvlinops/kfac_utils.py, test/cases.py, test/kfac_cases.py, test/test_gradient_moments.py, test/test_hessian.py, test/test_kfac.py, test/test_submatrix_on_curvatures.py, test/utils.py
This makes `curvlinops` support binary classification. Resolves #90
=> [ADD] Support `BCEWithLogitsLoss` in Fisher-MC and KFAC

curvlinops/kfac.py, test/test_kfac.py
Before this PR, we call `.backward()` on a tensor to trigger the backward hooks that compute the grad-output-based Kronecker factors of KFAC. 
As a side effect, this will compute `.grad` of all leafs of the tensor we are differentiating.
This is problematic for use cases in optimization that use the `.grad` attribute, which is modified though by creating a `KFACLinearOperator`. 
This PR changes the `.backward()` calls into `autograd.grad(...)` which does not modify any `.grad` attributes and therefore makes the computation of KFAC side effect free.
=> [REF] Make KFAC computation side effect free

curvlinops/_base.py, curvlinops/examples/functorch.py, curvlinops/experimental/activation_hessian.py, curvlinops/fisher.py, curvlinops/ggn.py, curvlinops/gradient_moments.py, curvlinops/hessian.py, curvlinops/inverse.py, curvlinops/jacobian.py, curvlinops/kfac.py, docs/examples/basic_usage/example_huggingface.py, setup.cfg, test/cases.py, test/conftest.py, test/kfac_cases.py, test/test__base.py, test/test_fisher.py, test/test_ggn.py, test/test_gradient_moments.py, test/test_hessian.py, test/test_inverse.py, test/test_jacobian.py, test/test_kfac.py, test/test_submatrix_on_curvatures.py, test/utils.py
Closes #86
@f-dangel @runame please give feedback and answer the question below. 
***Assumption:***
``` python
data: Union[Iterable[Tuple[Tensor, Tensor]], Iterable[Tuple[UserDict, Tensor]], Iterable[Tuple[dict, Tensor]]]
```
and there is an additional parameter in `_base._LinearOperator`:
``` python
batch_size_fn: Optional[Callable[[Any], int]] = None
```
where it must be non-`None` whenever `X` is not a `torch.Tensor`. 
This also fits well with Huggingface, although one must replace HF's default dataloader to outputs `(data, data['labels'])` instead of just `data`. Let me know if this should be considered.
***Code for testing the functionality:***
https://gist.github.com/wiseodd/426061afae24199446e60bfabc00e26e
I use `laplace-torch` there (two birds one stone), so just remove it if you …
=> Support arbitrary `X` in `data`

curvlinops/examples/functorch.py, curvlinops/fisher.py, curvlinops/gradient_moments.py, curvlinops/kfac.py, test/cases.py, test/conftest.py, test/test_gradient_moments.py, test/test_inverse.py, test/test_jacobian.py, test/test_kfac.py, test/test_submatrix_on_curvatures.py, test/utils.py
Resolves #108.
@f-dangel and me will investigate different definitions for the Fisher in these cases, but for now we will stick to the here implemented convention.
=> [FIX] Scaling of empirical/MC Fisher for output with more than two dimensions

curvlinops/fisher.py
=> [FIX] Scaling of MC Fisher for `MSELoss` and `BCEWithLogitsLoss` with mean reduction

curvlinops/submatrix.py, setup.cfg, test/test_submatrix.py
This is useful if we want to estimate the Frobenius norm of a sub-matrix `B = P1 A P2` where `P1, P2` are slicing matrices via Hutchinson trace-estimating `Tr(B^T B)`. We then need to define how to take the adjoint of a `SubmatrixLinearOperator`.
=> [ADD] Implement adjoint for sub-matrix linear operator

curvlinops/inverse.py, curvlinops/kfac.py, test/test_inverse.py, test/test_kfac.py, test/utils.py
Resolves #113.
I don't know if this covers all edge cases, but hopefully at least the most common use cases. For example, it is assumed that the user passes the right `params`, not sure if this can be avoided or if it is likely to lead to problems.
=> [ADD] `state_dict` functionality to `KFACLinearOperator` and `KFACInverseLinearOperator`

curvlinops/inverse.py, curvlinops/kfac.py, test/cases.py, test/conftest.py, test/kfac_cases.py, test/test_inverse.py, test/test_kfac.py
Since we added the `num_per_example_loss_terms` recently, we could remove the `loss_average` argument. I think there is no use case where it adds any additional benefit, and removing it will simplify the user experience significantly and it avoids user errors -- when the user doesn't pass any value for `num_per_example_loss_terms` it will still lead to the correct result, there will just be the overhead of one dataset pass.
Moreover, I created `Enums` for the string valued arguments in `KFACLinearOperator` (`FisherType` and `KFACType`) and added a custom `TypeVar` for the input/ouput of `torch_matmat`/`torch_matvec` to support static type checkers (this was a request by @BrunoKM).
=> Remove `loss_average` argument of `KFACLinearOperator`

curvlinops/__init__.py, curvlinops/kfac.py, test/test_kfac.py
Fixes #118.
Also, I have added the `FisherType` and `KFACType` Enums to `__init__` to make them easy to import.
=> [FIX] Checks if `Enum` contains string

curvlinops/norm/hutchinson.py
Instead of estimating the Frobenius norm by `v.T @ (A.T @ A @ v)`, use `w.T @ w` where `w = A @ v`. This 
1. halves the number of `matvec`s
2. improves numerical stability (result cannot be negative), and 
3. does not require the linear operator `A` to define `.T`.
=> [REF] Improve numerical stability of Frobenius estimator

.github/workflows/lint-black.yaml, .github/workflows/lint-darglint.yaml, .github/workflows/lint-flake8.yaml, .github/workflows/lint-isort.yaml, .github/workflows/lint-pydocstyle.yaml, .github/workflows/python-publish.yml, .github/workflows/test.yaml, .readthedocs.yaml, setup.cfg, setup.py
Had to explicitly install `packaging` and `wheels` in the CI because otherwise it would crash with an `ImportError` when trying to `import packaging` (note that only installing `packaging` was not sufficient).
=> [REF] Deprecate `pkg_resources`, use `importlib` & `packaging`

.conda_env.yml, .github/workflows/lint-black.yaml, .github/workflows/lint-darglint.yaml, .github/workflows/lint-flake8.yaml, .github/workflows/lint-isort.yaml, .github/workflows/lint-pydocstyle.yaml, .github/workflows/test.yaml, .readthedocs.yaml, changelog.md, curvlinops/diagonal/hutchinson.py, pyproject.toml
Python 3.8 will reach its end of life in October 2024.
Therefore, we will deprecate it and require at least Python 3.9 in future releases.
=> [REQ] Deprecate python 3.8

.github/workflows/lint-black.yaml, .github/workflows/lint-darglint.yaml, .github/workflows/lint-flake8.yaml, .github/workflows/lint-isort.yaml, .github/workflows/lint-pydocstyle.yaml, .github/workflows/python-publish.yml, .github/workflows/test.yaml, changelog.md
Minor maintenance that speeds up the GH action installations.
=> [CI] Update Github action versions, cache pip

.github/workflows/test.yaml, changelog.md, curvlinops/examples/utils.py, test/test_fisher.py
I noticed that the Monte-Carlo tests were not running anymore because we switched from `master` to `main`.
This PR re-activates them, slightly refactors them to make them faster, and adapts their tolerances to account for cases we added but never tested.
=> [CI | FIX] Improve and run Fisher-MC tests on `main`

curvlinops/_base.py
Addresses #135 by removing the conversion of the data iterable stored in `self._data` to and iterator with `iter()`.
=> Remove conversion of data Iterable to Iterator in `_LinearOperator`

curvlinops/_torch_base.py, test/test__torch_base.py
Long-term, I want to add native PyTorch support for linear operators in `curvlinops` to address inefficiencies like #71, but also to clearly separate PyTorch from SciPy so that it will be easier to tackle features like supporting distributed settings. 
This PR is a first step towards this goal.
From an API perspective, I plan to keep the constructor of all existing linear operators identical. The only backward-incompatible change will be that the produced linear operator will be purely PyTorch. To obtain the old behaviour one has to call `.to_scipy()` after the constructor.
**Old:** `H = HessianLinearOperator(...)`
**Planned new:** `H = HessianLinearOperator(...).to_scipy(dtype=...)`
The PR defines a linear operator interface in PyTorch which allows easy export to SciPy linear operators. …
=> [ADD] Minimal linear operator interface for PyTorch

curvlinops/_torch_base.py, curvlinops/examples/functorch.py, curvlinops/utils.py, docs/examples/basic_usage/example_inverses.py, test/test__torch_base.py
This PR introduces a class `CurvatureLinearOperator`, which is almost identical to the current base class `_LinearOperator`, but inherits from `PyTorchLinearOperator`.
The next steps will be to (i) migrate each linear operator to inherit from `CurvatureLinearOperator`, rather than `_LinearOperator`, (ii) delete `_LinearOperator`.
=> [REF] Replicate base class, but inherit from PyTorch linear operator

changelog.md, curvlinops/inverse.py, test/test_inverse.py
When `use_exact_damping=True` and `KFACLinearOperator._separate_weight_and_bias=True`, the damping will be repeatedly added to the eigenvalues corresponding to the bias parameters with every matrix-vector product.
=> [FIX] in-place damping bug in `KFACInverseLinearOperator`

changelog.md, curvlinops/kfac.py, test/test_inverse.py, test/utils.py
Follow up to #156, sorry, missed a test case.
_Edit: Added even more test cases and discovered and fixed a bug in KFAC's `load_state_dict` function._
=> [ADD] more test cases for inverse KFAC and fix bug in `KFAC.load_state_dict`
