docs/examples/basic_usage/example_matrix_vector_products.py
setup.cfg

And a comparison via `functorch`.

[DOC] Add example for Hessian-vector products

---

curvlinops/_base.py
docs/examples/basic_usage/example_matrix_vector_products.py

Add to example (computing the Hessian matrix via HMPs)

[ADD] Implement `matmat` via for-loop over `matvec`

---

docs/examples/basic_usage/example_matrix_vector_products.py

The comparison is done with `functorch`.

[DOC] Add example for GGNLinearOperator, visual comparison GGN vs. H

---

curvlinops/_base.py
curvlinops/ggn.py
curvlinops/hessian.py
docs/examples/basic_usage/example_matrix_vector_products.py
test/test___init__.py

Removes unnecessary arguments, broadens support for functional models and losses.

[BREAKING] Simplify interface

---

.readthedocs.yaml
docs/examples/basic_usage/example_model_merging.py

Adds an example for Fisher-averaging.

[DOC] Example on Fisher-averaging

---

curvlinops/__init__.py
curvlinops/trace/meyer2020hutch.py
docs/rtd/linops.rst
test/trace/test_meyer2020hutch.py

[ADD] Implement Hutch++ trace estimation

---

curvlinops/kfac.py
makefile
test/test_kfac.py

[ADD] Allow subsets of parameters (weight-only, bias-only) in KFAC

---

curvlinops/kfac.py

[FIX] Typo

---

.github/workflows/python-publish.yml
LICENSE
README.md
changelog.md
setup.cfg

A few pre- and post-merge TODOs:

[DOC] Update changelog & contributors, fix PyPI upload, prepare `1.2.0`

---

curvlinops/inverse.py
curvlinops/kfac.py
test/test_kfac.py

Manually verified the GPU test works.

[REF | KFAC] Use module names instead of `data_ptr()`s for mapping

---

docs/rtd/conf.py

[DOC] Add links to source code

---

curvlinops/gradient_moments.py

This PR addresses an efficiency problem in the empirical Fisher, similar to that described in #83 for the MC Fisher.
Remove for-loop over data and use GGN-vector products of a pseudo-loss instead which parallelizes the loop.

[REF] Improve efficiency of empirical Fisher

---

curvlinops/fisher.py

Applies the refactoring described in and resolves #83.
Replaces the expensive `autograd` loops over MC samples and data points via a cheaper internal loop over them (which might be refactored further in the future). Computes a GGNVP with a pseudo-loss whose GGN matches the MC Fisher. This approach costs as much as multiplying with the exact Fisher/GGN, but is more parallel and therefore usually much faster.
@runame please check if this fixes your performance problems before reviewing/merging.

[REF] Remove for-loop over samples in MC Fisher

---

curvlinops/gradient_moments.py

Applies the refactoring described in and closes #87.

[REF] Parallelize `grad_output` computation in empirical Fisher

---

curvlinops/fisher.py

Parallelizes the loop over data points and MC samples in the method that draws 'would-be' gradients from the model's likelihood. Speeds up `FisherMCLinearOperator`. Please check if the docstrings are up-to-date.

[REF] Parallelize `sample_grad_output` in MC Fisher

---

.github/workflows/lint-black.yaml
.github/workflows/lint-darglint.yaml
.github/workflows/lint-flake8.yaml
.github/workflows/lint-isort.yaml
.github/workflows/lint-pydocstyle.yaml
.github/workflows/test.yaml

Updates the yaml files for GH actions which contained branch names we are not using anymore. Thanks @andres-fr.

[CI] Run GH actions for PR to any branch

---

curvlinops/inverse.py
curvlinops/kfac.py
test/cases.py
test/conftest.py
test/test_inverse.py
test/test_kfac.py

[FIX] Output shapes of KFAC's `matmat`/`matvec`

---

changelog.md
docs/examples/basic_usage/example_visual_tour.py
pyproject.toml

Adds the block-diagonal Hessian, MC-Fisher, and KFAC to the visual tour tutorial.
Prettifies the visualizations using `tueplots`.

[DOC] Add more matrices to visual tour, prettify plots with `tueplots`

---

changelog.md
docs/rtd/conf.py

[DOC] Add `intersphinx` mapping to `curvlinops` objects

---

changelog.md
docs/examples/basic_usage/example_verification_spectral_density.py
docs/examples/basic_usage/example_visual_tour.py
pyproject.toml

Please review #134 first.
Uses `tueplots` to make the plots in the spectral density tutorial prettier.

[DOC] Prettify plots in spectral density tutorial

---

changelog.md
curvlinops/inverse.py
test/test_inverse.py

Fix default value in `LSMRInverseLinearOperator`

---

changelog.md
test/test_fisher.py
test/test_ggn.py
test/test_gradient_moments.py
test/test_hessian.py
test/test_inverse.py
test/test_jacobian.py
test/test_kfac.py
test/utils.py

[ADD] Test two consecutive matvecs of a linear operator
